apiVersion: v1
data:
  adminAccountEnabled: "true"
  adminAccountTokenTtl: 24h
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/name: kargo
  name: kargo-cm