---
apiVersion: v1
data:
  accounts.admin: login
  dex.config: |
    connectors:
      - type: saml
        id: saml
        name: SAML
        config:
          ssoURL: https://dev-90026493.okta.com/app/dev-90026493_argocd_2/exknrw0jalM4o4PcC5d7/sso/saml
          redirectURI: https://76thom3s07c2igh1.cd.akuity.cloud/api/dex/callback
          usernameAttr: email
          emailAttr: email
          groupsAttr: group
          caData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURxRENDQXBDZ0F3SUJBZ0lHQVpXRlorMElNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1JR1VNUXN3Q1FZRFZRUUdFd0pWVXpFVE1CRUcKQTFVRUNBd0tRMkZzYVdadmNtNXBZVEVXTUJRR0ExVUVCd3dOVTJGdUlFWnlZVzVqYVhOamJ6RU5NQXNHQTFVRUNnd0VUMnQwWVRFVQpNQklHQTFVRUN3d0xVMU5QVUhKdmRtbGtaWEl4RlRBVEJnTlZCQU1NREdSbGRpMDVNREF5TmpRNU16RWNNQm9HQ1NxR1NJYjNEUUVKCkFSWU5hVzVtYjBCdmEzUmhMbU52YlRBZUZ3MHlOVEF6TVRFeE16TXhNVFZhRncwek5UQXpNVEV4TXpNeU1UVmFNSUdVTVFzd0NRWUQKVlFRR0V3SlZVekVUTUJFR0ExVUVDQXdLUTJGc2FXWnZjbTVwWVRFV01CUUdBMVVFQnd3TlUyRnVJRVp5WVc1amFYTmpiekVOTUFzRwpBMVVFQ2d3RVQydDBZVEVVTUJJR0ExVUVDd3dMVTFOUFVISnZkbWxrWlhJeEZUQVRCZ05WQkFNTURHUmxkaTA1TURBeU5qUTVNekVjCk1Cb0dDU3FHU0liM0RRRUpBUllOYVc1bWIwQnZhM1JoTG1OdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0MKZ2dFQkFMZkEyZzc5SWtOS0x6UFJvVTN4Zk14RndlVisvV1M4Mzk4OUpJTWdkOFdJbHFGSE9OUmdyWk5UdjE2YzFhbThRM0t4eXZtVworN2NMY3d4OHVuZGJwZWY4QnFBUUkyaUprMER5SkRiRmlVR2hEaUdyTjhKYW9rWHk0NXRSbFlwVkVSVVlRbUROUVR6NExQR3JxV0ZJCjBLRlhnUFVnWXJSUFA3M0ZrRytpN0hja3lyUXJuaEw4bHhJSS9VbDRqUkJ6dU50QVNmVlVrOWJVajMwcW85TmpRZS9lZXZuekJLN04KeVFjOVducU5teWw0TTF4bGR3c1NUUjBHMDJMMDZ3c3k5K0FzdnJoQW1OVllEbUh0N2ZpN1ZhS01OcW1Tc1RPMzZOZGlkYVZJVWlSbgp2QlRTWlFLZWhsdnlBVU9UTkdXS3h6aCsweHhhY2Z3SWNKZ0ZZY0lqODE4Q0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCklXNVZ4Mlllc0k5TGo0RlVYSU5peHF6RTRFZUROV2tsdmh2Umc5elRzK01rVWk3VmVKa2dCd2pFL0RDM3Jkb2gvZTJ6eUE0YVF6T2MKVHdKdWZYNFNyVkd3QjdhRjBZK2ViSzU1Y1MrL09xVis1cEE3dXRybjVlNEk1cSt3TkFodklBeUdRRFl1ZnN0R3NsWDFIRjF2bmZSMApEVkEzOTF4aWpZUzAzTVZ5MjNUanZPajRFYmdwcTZUM0dUVE5NdFN2bDJMOW82bjMrL3hESzZqRVEvOTVCUzI0dStBZ3ducFhsQ3VFCk1JNUNObXB6dFlucmRFajdFWXBrN3B3RmZoUzNsTzhPUm5hU2tOWS9QbWUzUTZBQTZMUWtOSXNxUXpWQlJRNFJaMTd2MTlPaU5JdHIKUnBveFZZbHVXb3Q2MmE2Z0RWMEx1aGRBUmM4bWJuN3BSd1FDbWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  exec.enabled: "false"
  ga.anonymizeusers: "false"
  helm.enabled: "true"
  kustomize.enabled: "true"
  server.rbac.log.enforce.enable: "false"
  statusbadge.enabled: "false"
  ui.bannerpermanent: "false"
  users.anonymous.enabled: "false"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm